export const ULTRA_BEASTS = new Set([
  "nihilego",
  "buzzwole",
  "pheromosa",
  "xurkitree",
  "celesteela",
  "kartana",
  "guzzlord",
  "poipole",
  "naganadel",
  "stakataka",
  "blacephalon",
]);

export const PARADOX_NAMES = new Set([
  "great-tusk",
  "scream-tail",
  "brute-bonnet",
  "flutter-mane",
  "slither-wing",
  "roaring-moon",
  "sandy-shocks",
  "walking-wake",
  "gouging-fire",
  "raging-bolt",
  "iron-treads",
  "iron-bundle",
  "iron-hands",
  "iron-jugulis",
  "iron-moth",
  "iron-thorns",
  "iron-valiant",
  "iron-leaves",
  "iron-boulder",
  "iron-crown",
  "koraidon",
  "miraidon",
  "bloodmoon-ursaluna",
]);

export const BABY_NAMES = new Set([
  "pichu",
  "cleffa",
  "igglybuff",
  "togepi",
  "tyrogue",
  "smoochum",
  "elekid",
  "magby",
  "azurill",
  "wynaut",
  "budew",
  "chingling",
  "bonsly",
  "mime-jr",
  "happiny",
  "munchlax",
  "riolu",
  "mantyke",
  "toxel",
]);

export const REGIONAL_TOKENS = new Set([
  "alola",
  "alolan",
  "galar",
  "galarian",
  "hisui",
  "hisuan",
  "paldea",
  "paldean",
  "kanto",
  "johto",
  "hoenn",
  "sinnoh",
  "unova",
  "kalos",
]);


