#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");
const DIST_DIR = path.join(ROOT_DIR, "dist");
const SITEMAP_PATH = path.join(DIST_DIR, "sitemap.xml");
const BASE_URL = "https://pokedexdb.com";

const fetchPokemonList = async () => {
  const response = await fetch("https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0", {
    headers: { "User-Agent": "pokedexdb-sitemap-generator/1.0" },
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch Pokemon index: ${response.status} ${response.statusText}`);
  }
  const json = await response.json();
  if (!json || !Array.isArray(json.results)) {
    throw new Error("Unexpected payload from Pokemon index endpoint");
  }
  return json.results
    .filter((entry) => entry?.name && !entry.name.includes("totem"))
    .map((entry) => entry.name)
    .filter(Boolean)
    .sort();
};

const escapeXml = (value) => {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
};

const generateSitemap = async () => {
  const pokemonList = await fetchPokemonList();
  const now = new Date().toISOString().split("T")[0];
  
  const urls = [
    // Homepage
    `    <url>
      <loc>${escapeXml(BASE_URL)}/</loc>
      <lastmod>${now}</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
    </url>`,
    // Other main pages (based on routing in main.jsx)
    `    <url>
      <loc>${escapeXml(BASE_URL)}/#/home</loc>
      <lastmod>${now}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>`,
    `    <url>
      <loc>${escapeXml(BASE_URL)}/#/items</loc>
      <lastmod>${now}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>`,
    `    <url>
      <loc>${escapeXml(BASE_URL)}/#/moves</loc>
      <lastmod>${now}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>`,
    `    <url>
      <loc>${escapeXml(BASE_URL)}/#/abilities</loc>
      <lastmod>${now}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>`,
    `    <url>
      <loc>${escapeXml(BASE_URL)}/#/whosthat</loc>
      <lastmod>${now}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.7</priority>
    </url>`,
    // Pokemon pages (static pages generated by generate-share-pages.mjs)
    ...pokemonList.map(
      (name) => `    <url>
      <loc>${escapeXml(`${BASE_URL}/${encodeURIComponent(name)}`)}</loc>
      <lastmod>${now}</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.9</priority>
    </url>`
    ),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>`;

  await writeFile(SITEMAP_PATH, xml, "utf8");
  console.log(`Generated sitemap.xml with ${urls.length} URLs.`);
};

generateSitemap().catch((error) => {
  console.error("Failed to generate sitemap:", error);
  process.exitCode = 1;
});

